from datetime import datetime


def generate_report(industry, confidence, analysis):

    report = f"""
========================================

        AI RESUME ANALYSIS REPORT

========================================


Generated Date:
{datetime.now().strftime("%d-%m-%Y")}


----------------------------------------

INDUSTRY RECOMMENDATION

----------------------------------------

Recommended Industry:
{industry}


Prediction Confidence:
{confidence:.2f}%



----------------------------------------

RESUME EVALUATION

----------------------------------------

Resume Score:
{analysis['resume_score']}/100


ATS Score:
{analysis['ats_score']}/100


Rating:
{analysis['rating']}



----------------------------------------

MATCHED SKILLS

----------------------------------------

"""


    for skill in analysis["matched_skills"]:

        report += f"✓ {skill}\n"


    report += """

----------------------------------------

MISSING SKILLS

----------------------------------------

"""


    for skill in analysis["missing_skills"]:

        report += f"✗ {skill}\n"



    report += """

----------------------------------------

STRENGTHS

----------------------------------------

"""


    for item in analysis["strengths"]:

        report += f"• {item}\n"



    report += """

----------------------------------------

AREAS TO IMPROVE

----------------------------------------

"""


    for item in analysis["weaknesses"]:

        report += f"• {item}\n"



    report += """

----------------------------------------

RECOMMENDATIONS

----------------------------------------

"""


    for item in analysis["recommendations"]:

        report += f"• {item}\n"



    report += """

========================================

Generated by AI Resume Analyzer

========================================
"""


    return report